### ISSUE TITLE
Issue with using the code 

### ISSUE THREAD

**Issue by sfenelli** [Nimrod-Galor/Simple-Bitcoin-Ticker#1]
Hi!!!
How are you?

Since yesterday I am experimenting some issues with the ticker...

:46:01.208 -> Date: Mon, 29 Mar 2021 11:46:02 GMT
08:46:01.208 -> Content-Type: application/json; charset=utf-8
08:46:01.208 -> Transfer-Encoding: chunked
08:46:01.208 -> Connection: close
08:46:01.208 -> Set-Cookie: __cfduid=dcc47c40bbe1b68f90f2f9a8f6f00e78f1617018361; expires=Wed, 28-Apr-21 11:46:01 GMT; path=/; domain=.coinmarketcap.com; HttpOnly; SameSite=Lax; Secure
08:46:01.208 -> vary: origin,accept-encoding
08:46:01.208 -> cache-control: no-cache
08:46:01.208 -> CF-Cache-Status: DYNAMIC
08:46:01.208 -> cf-request-id: 091f6730120000f2035e055000000001
08:46:01.255 -> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
08:46:01.255 -> Server: cloudflare
08:46:01.255 -> CF-RAY: 6378daf9bf39f203-GRU
08:46:01.255 ->
08:46:01.255 -> 5b8
08:46:01.303 -> {"status":{"timestamp":"2021-03-29T11:46:02.321Z","error_code":0,"error_message":null,"elapsed":18,"credit_count":1,"notice":null},"data":{"BTC":{"id":1,"name":"Bitcoin","symbol":"BTC","slug":"bitcoin","num_market_pairs":9471,"date_added":"2013-04-28T00:00:00.000Z","tags":["mineable","pow","sha-256","store-of-value","state-channels","coinbase-ventures-portfolio","three-arrows-capital-portfolio","polychain-capital-portfolio","binance-labs-portfolio","arrington-xrp-capital","blockchain-capital-portfolio","boostvc-portfolio","cms-holdings-portfolio","dcg-portfolio","dragonfly-capital-portfolio","electric-capital-portfolio","fabric-ventures-portfolio","framework-ventures","galaxy-digital-portfolio","huobi-capital","alameda-research-portfolio","a16z-portfolio","1confirmation-portfolio","winklevoss-capital","usv-portfolio","placeholder-ventures-portfolio","pantera-capital-portfolio","multicoin-capital-portfolio","paradigm-xzy-screener"],"max_supply":21000000,"circulating_supply":18667718,"total_supply":18667718,"is_active":1,"platform":null,"cmc_rank":1,"is_fiat":0,"last_updated":"2021-03-29T11:45:02.000Z","quote":{"USD":{"price":57935.909019262865,"volume_24h":54247443627.20762,"percent_change_1h":0.38435914,"percent_change_24h":3.17173716,"percent_change_7d":-0.38657157,"percent_change_30d":23.42378904,"percent_change_60d":84.61885447,"percent_change_90d":116.7252174,"market_cap":1081531211645.2557,"last_updated":"2021-03-29T11:45:02.000Z"}}}}}
08:46:01.443 -> 0
08:46:01.443 ->
08:46:01.443 -> Deserialization failed
08:46:01.443 -> Not enough memorydoc capacity:

Any Idea how to solve it?
Thanks in advance

**Comment by sfenelli** [comment]
New error...
Maybe it will help to solve it.​
​
​09:05:12.567 -> connecting to pro-api.coinmarketcap.com
09:05:12.567 -> Using fingerprint '335b4fc7b2e210256ed6f2f900744ea21f436195'
09:05:34.281 -> connection failed
09:05:34.281 -> connecting to pro-api.coinmarketcap.com
09:05:34.281 -> Using fingerprint '335b4fc7b2e210256ed6f2f900744ea21f436195'
09:05:49.752 -> requesting URL: /v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=c6e48ded-54e1-4c8a-8cfa-c1a15043f72e&symbol=BTC&convert=USD
09:05:50.033 -> request sent
09:05:55.032 -> Unexpected response:
09:05:55.032 ->

**Comment by sfenelli** [comment]
Problem Solved...

  // parse response
  DynamicJsonDocument jsonDocument(2024);

Changed to
  // parse response
  DynamicJsonDocument jsonDocument(3500);

Now the capacity is huge enough. 

And json library updated to last version. 

Hope to help someone with the same problem...

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @sfenelli)
